/**
 * HMM EXPLORER – PART 1: HMM BASICS
 * =================================
 * A two-state HMM (CpG islands or the dishonest casino): generating a
 * sequence, the probability of one path, Viterbi, Forward, posterior
 * decoding and learning the parameters (counting, Baum–Welch).
 */
class HmmBasics {
    constructor(app) {
        this.app = app; this.H = HmmEngine; this.V = HmmViews;
        this.$ = id => document.getElementById(id);
        this.box = this.$('basics-content');
        this.step = 1;
        this.trellis = { viterbi: { mode: 'full', k: 0, sel: null }, forward: { mode: 'full', k: 0, sel: null } };
        this.showTruth = true;
        this.bestRevealed = false;
        this.anim = null;
        this.trainN = 10;

        const sel = this.$('b-model');
        for (const [key, m] of Object.entries(HMM_MODELS)) sel.add(new Option(m.name, key));
        sel.addEventListener('change', () => this.loadPreset(sel.value));
        for (const k of [0, 1]) this.$('b-stay' + k).addEventListener('input', () => this.setStay(k, +this.$('b-stay' + k).value));
        this.$('b-reset-model').addEventListener('click', () => this.loadPreset(this.presetKey, true));
        this.$('b-length').addEventListener('input', () => { this.$('b-length-value').textContent = this.$('b-length').value; });
        this.$('b-length').addEventListener('change', () => this.generate());
        this.$('b-generate').addEventListener('click', () => this.generate());
        this.$('b-use-own').addEventListener('click', () => this.useOwn());
        this.$('b-own').addEventListener('keydown', e => { if (e.key === 'Enter') this.useOwn(); });
        this.box.addEventListener('click', e => this.onClick(e));
        this.box.addEventListener('mousedown', e => this.onPaintStart(e));
        this.box.addEventListener('mouseover', e => this.onPaintMove(e));
        document.addEventListener('mouseup', () => { this.painting = null; });
        this.loadPreset('cpg');
    }

    // ------------------------------------------------------------ model & sequence
    loadPreset(key, keepSeq = false) {
        this.presetKey = key;
        const p = HMM_MODELS[key];
        this.model = this.H.normalizeModel(JSON.parse(JSON.stringify({ alphabet: p.alphabet, states: p.states, start: p.start, trans: p.trans })));
        this.$('b-model').value = key;
        this.syncControls();
        if (!keepSeq || !this.seq || [...this.seq].some(c => !p.alphabet.includes(c))) {
            this.$('b-length').value = p.length; this.$('b-length-value').textContent = p.length;
            this.generate();
        } else this.recompute();
    }

    syncControls() {
        const m = this.model;
        for (const k of [0, 1]) {
            document.querySelectorAll('.b-name' + k).forEach(el => { el.textContent = m.states[k].name; });
            this.$('b-stay' + k).value = m.trans[k][k];
            this.$(`b-stay${k}-value`).textContent = m.trans[k][k].toFixed(3);
        }
        const A = m.alphabet.split('');
        let h = '<table class="hm-emit"><tr><th></th>' + A.map(a => `<th>${a}</th>`).join('') + '</tr>';
        m.states.forEach((st, k) => {
            h += `<tr><th style="color:${st.color}">${this.V.esc(st.name)}</th>` + A.map(a => `<td><input type="number" step="0.01" min="0" max="1" data-k="${k}" data-a="${a}" value="${st.emit[a].toFixed(3)}"></td>`).join('') + '</tr>';
        });
        this.$('b-emit').innerHTML = h + '</table>';
        this.$('b-emit').querySelectorAll('input').forEach(inp => {
            const apply = () => { const v = Math.max(0, parseFloat(inp.value) || 0); this.model.states[+inp.dataset.k].emit[inp.dataset.a] = v; this.H.normalizeModel(this.model); this.syncControls(); this.recompute(); };
            inp.addEventListener('change', apply);
        });
    }

    setStay(k, v) {
        this.model.trans[k][k] = v; this.model.trans[k][1 - k] = 1 - v;
        this.$(`b-stay${k}-value`).textContent = v.toFixed(3);
        this.recompute();
    }

    generate() {
        this.stopAnim();
        const L = +this.$('b-length').value;
        const rng = new this.H.Rng((Math.random() * 1e9) | 0);
        const s = this.H.sample(this.model, L, rng);
        this.seq = s.seq; this.truePath = s.path;
        this.$('b-seqinfo').textContent = `Generated by the model: ${L} symbols, the hidden path is known (for checking).`;
        this.newSequence();
    }

    useOwn() {
        const A = this.model.alphabet;
        const s = this.$('b-own').value.toUpperCase().split('').filter(c => A.includes(c)).join('');
        if (s.length < 2) { this.app.toast(`Type at least two symbols from ${A}.`); return; }
        this.stopAnim();
        this.seq = s.slice(0, 1000); this.truePath = null;
        this.$('b-seqinfo').textContent = `Your sequence: ${this.seq.length} symbols; the true path is unknown.`;
        this.newSequence();
    }

    newSequence() {
        this.userPath = new Array(this.seq.length).fill(0);
        this.bestRevealed = false;
        for (const t of Object.values(this.trellis)) { t.k = 0; t.sel = null; }
        this.recompute();
    }

    recompute() {
        if (!this.seq) return;
        this.vit = this.H.viterbi(this.model, this.seq);
        this.post = this.H.posterior(this.model, this.seq);
        this.showStep(this.step);
    }

    // ------------------------------------------------------------ helpers
    name(k) { const st = this.model.states[k]; return `<span class="hm-sname" style="color:${st.color}">${this.V.esc(st.name)}</span>`; }
    l10(lnp, d = 2) { return this.V.fmtLog10(lnp, d); }
    accuracy(path) { if (!this.truePath) return null; let c = 0; path.forEach((s, i) => { if (s === this.truePath[i]) c++; }); return c / path.length; }
    tooLong() { return this.seq.length > 60; }
    runs(path) {
        const out = this.model.states.map(() => []);
        let start = 0;
        for (let i = 1; i <= path.length; i++) if (i === path.length || path[i] !== path[i - 1]) { out[path[start]].push(i - start); start = i; }
        return out;
    }

    showStep(n) {
        this.step = Math.max(1, Math.min(7, n));
        this.app.setPills('basics', this.step);
        if (this.step !== 2) this.stopAnim();
        this.box.innerHTML = [null, this.stepModel, this.stepGenerate, this.stepPath, this.stepViterbi, this.stepForward, this.stepPosterior, this.stepLearning][this.step].call(this);
        if (this.step === 7 && this.training) this.renderTraining();
    }

    // ------------------------------------------------------------ step 1
    stepModel() {
        const p = HMM_MODELS[this.presetKey], m = this.model;
        return `<h3>What is hidden, what is observed</h3>
            <p>${p.story}</p>
            <div class="hm-diagram-wrap">${this.V.basicDiagram(m)}</div>
            <p>A <strong>hidden Markov model</strong> (HMM) describes such data as the output of a process that moves between a few <strong>hidden states</strong>. Here there are two: ${this.name(0)} and ${this.name(1)}.</p>
            <ul class="hm-list">
                <li>Each state has its own <strong>emission probabilities</strong> e<sub>k</sub>(b): the probability of producing symbol b while in state k (bars under the circles). ${this.name(1)} prefers ${this.favourite(1)}, ${this.name(0)} prefers ${this.favourite(0)}.</li>
                <li>After emitting a symbol the process moves to the next state according to the <strong>transition probabilities</strong> a<sub>kl</sub> (arrows; thicker = more probable). The loops mean "stay in the same state".</li>
                <li><strong>Start probabilities</strong> a<sub>0k</sub> say where the process begins.</li>
            </ul>
            <p>The model makes two simplifying assumptions: the next state depends only on the current state (the <strong>Markov property</strong>), and a symbol depends only on the state that emits it. That is all – and it is exactly what makes fast dynamic programming possible later.</p>
            <h4>Notation used in this app</h4>
            <table class="bl-table hm-notation">
                <tr><td>x = x<sub>1</sub> … x<sub>L</sub></td><td>the observed sequence</td></tr>
                <tr><td>π = π<sub>1</sub> … π<sub>L</sub></td><td>a path: one hidden state for every position</td></tr>
                <tr><td>a<sub>kl</sub></td><td>probability of moving from state k to state l</td></tr>
                <tr><td>e<sub>k</sub>(b)</td><td>probability that state k emits symbol b</td></tr>
            </table>
            <h4>Three questions an HMM can answer</h4>
            <ol class="hm-list">
                <li><strong>Decoding</strong> – which states produced this sequence? The single most probable path: <em>Viterbi</em> (step 4). The probability of each state at each position: <em>posterior decoding</em> (step 6).</li>
                <li><strong>Scoring</strong> – how probable is the sequence under the model, summed over all paths? <em>Forward algorithm</em> (step 5). This is how a profile HMM decides whether a protein belongs to a family (part 3).</li>
                <li><strong>Learning</strong> – where do the probabilities come from? Counting in labelled data, or <em>Baum–Welch</em> when the paths are unknown (step 7).</li>
            </ol>
            ${this.V.lesson(`<strong>Why "hidden"?</strong> An ordinary Markov chain over the letters would model only which letter follows which. An HMM adds a layer we cannot see – island or not, fair or loaded, and later: match, insert or delete. Inferring that layer is the whole point. <br><span class="dp-hint">${p.note}</span>`)}`;
    }

    favourite(k) {
        const st = this.model.states[k];
        const A = this.model.alphabet.split('');
        const top = A.slice().sort((a, b) => st.emit[b] - st.emit[a]);
        const best = st.emit[top[0]];
        const tied = top.filter(a => Math.abs(st.emit[a] - best) < 1e-6);
        return tied.length === A.length ? 'no symbol (all equally likely)' : tied.join(' and ');
    }

    // ------------------------------------------------------------ step 2
    stepGenerate() {
        const m = this.model;
        const r = this.runs(this.truePath || this.vit.path);
        const stats = m.states.map((st, k) => `<tr><td>${this.name(k)}</td><td>${r[k].length}</td><td>${r[k].length ? (r[k].reduce((a, b) => a + b, 0) / r[k].length).toFixed(1) : '–'}</td><td>${(1 / (1 - m.trans[k][k])).toFixed(1)}</td></tr>`).join('');
        return `<h3>An HMM is a machine that generates sequences</h3>
            <p>To produce a sequence the model repeats two moves: <strong>choose the next state</strong> (using the transition probabilities), then <strong>emit a symbol</strong> from that state's distribution. Watch it:</p>
            <div class="dp-buttons input-controls">
                <button class="primary" data-act="animate">▶ Generate step by step</button>
                <button data-act="generate">Generate at once</button>
                <button data-act="toggle-truth">${this.showTruth ? 'Hide' : 'Show'} the hidden path</button>
            </div>
            <div class="hm-gen">
                <div id="b-gen-diagram" class="hm-diagram-wrap">${this.V.basicDiagram(m)}</div>
                <div id="b-gen-strip">${this.genStrip(this.seq.length)}</div>
            </div>
            ${this.truePath ? `<h4>Segments in this sequence</h4>
            <table class="bl-table hm-narrow"><tr><th>state</th><th>segments</th><th>mean length</th><th>expected 1/(1−a<sub>kk</sub>)</th></tr>${stats}</table>` : '<p class="dp-hint">This sequence was typed in, so its hidden path is unknown. Generate one to see the path.</p>'}
            ${this.V.lesson(`The colours are the <strong>hidden path</strong>. Real data come without them – press <em>Hide the hidden path</em> and try to guess where the ${this.presetKey === 'cpg' ? 'islands are' : 'loaded die was used'}. The stay probabilities set the segment lengths (try the sliders), the emission probabilities set how different the segments look. The more different they look, the easier the path is to recover.`)}`;
    }

    genStrip(upto) {
        const path = this.showTruth && this.truePath ? this.truePath.slice(0, upto) : null;
        const legend = this.model.states.map((st, k) => `<span><i style="background:${st.color}"></i>${this.V.esc(st.name)}</span>`).join('');
        return `${this.V.seqStrip(this.seq.slice(0, upto), path, this.model, { label: 'x' })}<div class="bl-legend hm-legend">${legend}</div>`;
    }

    animate() {
        this.generate();
        this.showTruth = true;
        this.showStep(2);
        let i = 0;
        const L = this.seq.length;
        const tick = () => {
            if (i >= L) { this.stopAnim(); this.showStep(2); return; }
            const d = this.$('b-gen-diagram'), s = this.$('b-gen-strip');
            if (!d || !s) { this.stopAnim(); return; }
            d.innerHTML = this.V.basicDiagram(this.model, { active: this.truePath[i], lastSymbol: this.seq[i] });
            s.innerHTML = this.genStrip(i + 1);
            i++;
        };
        this.$('b-gen-strip').innerHTML = this.genStrip(0);
        this.anim = setInterval(tick, L > 80 ? 60 : 160);
    }
    stopAnim() { if (this.anim) { clearInterval(this.anim); this.anim = null; } }

    // ------------------------------------------------------------ step 3
    stepPath() {
        const m = this.model, L = this.seq.length;
        const J = this.H.joint(m, this.seq, this.userPath);
        const best = this.vit.logp;
        const naive = J.terms.reduce((p, t) => p * t.p, 1);
        const shown = J.terms.slice(0, 12);
        const factors = shown.map(t => t.kind === 'emit'
            ? `<td class="hm-fac">e<sub>${this.V.esc(m.states[t.state].key)}</sub>(${t.symbol}) = ${t.p.toFixed(3)}</td>`
            : `<td class="hm-fac hm-fac-t">${t.kind === 'start' ? `a<sub>0,${this.V.esc(m.states[t.to].key)}</sub>` : `a<sub>${this.V.esc(m.states[t.from].key)}${this.V.esc(m.states[t.to].key)}</sub>`} = ${t.p.toFixed(3)}</td>`).join('<td class="hm-times">×</td>');
        const truthBtn = this.truePath ? '<button data-act="path-true">the true path</button>' : '';
        const diff = (best - J.logp) / Math.LN10;
        return `<h3>The probability of one path</h3>
            <p>If we <em>knew</em> the path, the probability of observing the sequence along that path would simply be the product of all the moves the model made:</p>
            <p class="hm-formula">P(x, π) = a<sub>0π₁</sub> · e<sub>π₁</sub>(x₁) · a<sub>π₁π₂</sub> · e<sub>π₂</sub>(x₂) · … · a<sub>π<sub>L−1</sub>π<sub>L</sub></sub> · e<sub>π<sub>L</sub></sub>(x<sub>L</sub>)</p>
            <p><strong>Your turn:</strong> click a symbol (or drag across several) to switch its state. Try to find the path that makes the sequence most probable.</p>
            ${this.V.seqStrip(this.seq, this.userPath, m, { label: 'your π', clickable: true, cls: 'hm-paint' })}
            ${this.truePath && this.bestRevealed ? this.V.pathStrip(this.truePath, m, 'true π') : ''}
            <div class="dp-buttons input-controls hm-tight">
                <button data-act="path-all" data-k="0">all ${this.V.esc(m.states[0].name)}</button>
                <button data-act="path-all" data-k="1">all ${this.V.esc(m.states[1].name)}</button>
                ${this.bestRevealed ? truthBtn + '<button data-act="path-best">the best path (Viterbi)</button>' : '<button data-act="reveal">Reveal the best possible score</button>'}
            </div>
            <div class="hm-factors-wrap"><table class="hm-factors"><tr>${factors}${J.terms.length > shown.length ? '<td class="hm-times">× …</td>' : ''}</tr></table></div>
            <table class="bl-table hm-narrow">
                <tr><td>P(x, your π)</td><td><strong>${this.H.sci(J.logp)}</strong></td><td>log<sub>10</sub> = <strong>${this.l10(J.logp)}</strong></td></tr>
                ${this.bestRevealed ? `<tr><td>P(x, best π)</td><td>${this.H.sci(best)}</td><td>log<sub>10</sub> = ${this.l10(best)}</td></tr>
                <tr><td colspan="3">${diff < 1e-9 ? '🎉 You found the most probable path.' : `The best path is 10<sup>${diff.toFixed(2)}</sup> = ${Math.pow(10, diff) < 1e6 ? Math.pow(10, diff).toFixed(1) : '10^' + diff.toFixed(1)} times more probable than yours.`}</td></tr>` : ''}
                <tr><td>Number of possible paths</td><td colspan="2">${m.states.length}<sup>${L}</sup> ≈ 10<sup>${(L * Math.log10(m.states.length)).toFixed(1)}</sup></td></tr>
                <tr><td>The same product multiplied directly in floating point</td><td colspan="2">${naive === 0 ? '<strong class="dp-red">0 (underflow!)</strong>' : naive.toExponential(3)}</td></tr>
            </table>
            ${this.V.lesson(`<strong>Two lessons.</strong> (1) Every path has a probability, and there are ${m.states.length}<sup>L</sup> of them – far too many to try one by one even for short sequences; step 4 finds the best one without enumerating them. (2) Products of many numbers below 1 become astronomically small. With ${L} symbols the product is ${this.H.sci(J.logp)}; a computer's floating-point numbers stop at about 10<sup>−308</sup> (set the length to ~700 to see the direct product become 0). All HMM software therefore works with <strong>logarithms</strong>: log P(x, π) = Σ log a + Σ log e – a sum instead of a product. The tables in this app show log<sub>10</sub> values.`)}`;
    }

    // ------------------------------------------------------------ steps 4 and 5: the trellis
    trellisTable(kind) {
        const m = this.model, K = m.states.length, L = this.seq.length, st = this.trellis[kind];
        const M = kind === 'viterbi' ? this.vit.V : this.post.F;
        const filled = st.mode === 'step' ? st.k : K * L;
        const onPath = kind === 'viterbi' && filled >= K * L;
        let h = `<div class="hm-trellis-wrap"><table class="hm-trellis"><tr><th class="hm-corner">i</th>${[...this.seq].map((c, i) => `<th>${i + 1}</th>`).join('')}</tr>`;
        h += `<tr><th class="hm-corner">x<sub>i</sub></th>${[...this.seq].map(c => `<th class="hm-sym">${c}</th>`).join('')}</tr>`;
        for (let k = 0; k < K; k++) {
            h += `<tr><th class="hm-rowh" style="color:${m.states[k].color}">${this.V.esc(m.states[k].name)}</th>`;
            for (let i = 0; i < L; i++) {
                const idx = i * K + k;
                const cls = ['hm-cell'];
                let inner = '';
                if (idx < filled) {
                    let arrow = '';
                    if (kind === 'viterbi' && i > 0) { const p = this.vit.P[k][i]; arrow = p === k ? '→' : (p < k ? '↘' : '↗'); }
                    inner = `${arrow ? `<span class="hm-arrow">${arrow}</span>` : ''}${this.V.f2(M[k][i] / Math.LN10)}`;
                    if (onPath && this.vit.path[i] === k) { cls.push('hm-onpath'); }
                } else cls.push('hm-empty');
                if (st.mode === 'step' && idx === filled) cls.push('hm-current');
                if (st.sel && st.sel.k === k && st.sel.i === i) cls.push('hm-selcell');
                const style = onPath && this.vit.path[i] === k ? ` style="--pc:${m.states[k].color}"` : '';
                h += `<td class="${cls.join(' ')}" data-trellis="${kind}" data-k="${k}" data-i="${i}"${style}>${inner}</td>`;
            }
            h += '</tr>';
        }
        return h + '</table></div>';
    }

    cellExplain(kind, k, i) {
        const m = this.model, M = kind === 'viterbi' ? this.vit.V : this.post.F;
        const c = this.H.cellCandidates(m, this.seq, M, k, i);
        const e = c.emit / Math.LN10;
        const nm = this.name(k);
        const label = kind === 'viterbi' ? 'v' : 'f';
        if (i === 0) {
            const t = c.cands[0].trans / Math.LN10;
            return `<strong>${label}<sub>${this.V.esc(m.states[k].key)}</sub>(1)</strong> – first position, state ${nm}: start probability × emission.<br>
                log a<sub>0k</sub> + log e<sub>k</sub>(${this.seq[0]}) = ${this.V.f2(t)} + ${this.V.f2(e)} = <strong>${this.V.f2(M[k][0] / Math.LN10)}</strong>`;
        }
        const tot = c.cands.map(x => x.total);
        const best = tot.indexOf(Math.max(...tot));
        const lines = c.cands.map((x, j) => `<li class="${kind === 'viterbi' && j === best ? 'best' : ''}">from ${this.name(j)}: ${label}(${i}) + log a = ${this.V.f2(x.prev / Math.LN10)} + ${this.V.f2(x.trans / Math.LN10)} = ${this.V.f2(x.total / Math.LN10)}</li>`).join('');
        let combine;
        if (kind === 'viterbi') combine = `maximum = ${this.V.f2(tot[best] / Math.LN10)} (from ${this.name(best)})`;
        else { let s = this.H.NEG; for (const x of tot) s = this.H.logsum(s, x); combine = `sum of the probabilities: log<sub>10</sub>(${tot.map(x => '10<sup>' + this.V.f2(x / Math.LN10) + '</sup>').join(' + ')}) = ${this.V.f2(s / Math.LN10)}`; }
        return `<strong>${label}<sub>${this.V.esc(m.states[k].key)}</sub>(${i + 1})</strong> – state ${nm} at position ${i + 1} (symbol ${this.seq[i]}). Where can the path come from?
            <ul>${lines}</ul>
            ${combine}; then add the emission log e<sub>k</sub>(${this.seq[i]}) = ${this.V.f2(e)} → <strong>${this.V.f2(M[k][i] / Math.LN10)}</strong>`;
    }

    trellisControls(kind) {
        const st = this.trellis[kind], K = this.model.states.length, total = K * this.seq.length;
        const cur = st.mode === 'step' && st.k < total ? { k: st.k % K, i: Math.floor(st.k / K) } : null;
        const explainCell = cur || st.sel;
        return `<div class="at-step-controls">
                <label class="ms-check"><input type="radio" name="tm-${kind}" data-act="tmode" data-kind="${kind}" value="full" ${st.mode === 'full' ? 'checked' : ''}> whole table</label>
                <label class="ms-check"><input type="radio" name="tm-${kind}" data-act="tmode" data-kind="${kind}" value="step" ${st.mode === 'step' ? 'checked' : ''}> fill it step by step</label>
                ${st.mode === 'step' ? `<button data-act="tstep" data-kind="${kind}" data-n="1">Next cell</button><button data-act="tstep" data-kind="${kind}" data-n="${K}">Next column</button><button data-act="tstep" data-kind="${kind}" data-n="${total}">Finish</button><span class="dp-hint">${Math.min(st.k, total)} / ${total} cells</span>` : '<span class="dp-hint">Click a cell to see how it was computed.</span>'}
                <div class="at-step-explain">${explainCell ? this.cellExplain(kind, explainCell.k, explainCell.i) : ''}</div>
            </div>`;
    }

    stepViterbi() {
        const m = this.model;
        const acc = this.accuracy(this.vit.path);
        const done = this.trellis.viterbi.mode === 'full' || this.trellis.viterbi.k >= m.states.length * this.seq.length;
        return `<h3>Viterbi: the most probable path</h3>
            <p>We want the path π* with the highest P(x, π). The trick is the same as in Needleman–Wunsch: <strong>the best path ending in state l at position i must extend the best path ending in some state k at position i−1.</strong> So we only keep, for every state and position, the probability of the best path ending there:</p>
            <p class="hm-formula">v<sub>l</sub>(i) = e<sub>l</sub>(x<sub>i</sub>) · max<sub>k</sub> [ v<sub>k</sub>(i−1) · a<sub>kl</sub> ] &nbsp;&nbsp;→ in logs:&nbsp;&nbsp; log v<sub>l</sub>(i) = log e<sub>l</sub>(x<sub>i</sub>) + max<sub>k</sub> [ log v<sub>k</sub>(i−1) + log a<sub>kl</sub> ]</p>
            <p>The table (the <em>trellis</em>) has one row per state and one column per position; the arrow in a cell remembers which state the best path came from (→ same state, ↗/↘ switch). At the end we take the best cell of the last column and follow the arrows back: the <strong>traceback</strong>.</p>
            ${this.tooLong() ? '<p class="dp-hint">The trellis is drawn for sequences of up to 60 symbols – shorten the sequence to see it. The result is shown below.</p>' : this.trellisControls('viterbi') + this.trellisTable('viterbi')}
            ${done ? `<h4>Result</h4>
            ${this.V.seqStrip(this.seq, null, m, { label: 'x' })}
            ${this.V.pathStrip(this.vit.path, m, 'Viterbi π*')}
            ${this.truePath ? this.V.pathStrip(this.truePath, m, 'true π') : ''}
            <p>log<sub>10</sub> P(x, π*) = <strong>${this.l10(this.vit.logp)}</strong>${acc !== null ? `; the Viterbi path agrees with the true path at <strong>${(acc * 100).toFixed(0)} %</strong> of positions` : ''}. Your path in step 3: ${this.l10(this.H.joint(m, this.seq, this.userPath).logp)}.</p>` : ''}
            ${this.V.lesson(`<strong>Cost:</strong> K states × L positions cells, each looking at K predecessors: K²L operations instead of K<sup>L</sup> paths. For ${this.seq.length} symbols that is ${4 * this.seq.length} instead of ≈10<sup>${(this.seq.length * Math.log10(2)).toFixed(0)}</sup>. <strong>The best path is not the truth:</strong> short segments are often missed (a short run of GC-rich bases is not worth paying two switching penalties). Make the states more different (emission table) or stickier (sliders) and watch the agreement change.`)}`;
    }

    stepForward() {
        const m = this.model, f = this.post;
        const pBest = this.vit.logp - f.logp;
        const A = m.alphabet.split('');
        const nullLog = [...this.seq].reduce((s, c) => s + Math.log(1 / A.length), 0);
        const lo = (f.logp - nullLog) / Math.LN10;
        let shuffled = '';
        if (this.shuffled && this.shuffled.orig === this.seq) shuffled = this.shuffled.html;
        return `<h3>Forward: the probability of the sequence</h3>
            <p>Often we do not care about one particular path but about the probability that the model produces the sequence <em>at all</em>, whichever path it takes:</p>
            <p class="hm-formula">P(x) = Σ<sub>π</sub> P(x, π)</p>
            <p>The <strong>Forward algorithm</strong> computes this sum with exactly the same table as Viterbi – only <em>max</em> is replaced by <em>sum</em>. f<sub>l</sub>(i) is the total probability of all paths that emit x<sub>1</sub>…x<sub>i</sub> and end in state l:</p>
            <p class="hm-formula">f<sub>l</sub>(i) = e<sub>l</sub>(x<sub>i</sub>) · Σ<sub>k</sub> f<sub>k</sub>(i−1) · a<sub>kl</sub> &nbsp;&nbsp;&nbsp; P(x) = Σ<sub>k</sub> f<sub>k</sub>(L)</p>
            ${this.tooLong() ? '<p class="dp-hint">The table is drawn for sequences of up to 60 symbols.</p>' : this.trellisControls('forward') + this.trellisTable('forward')}
            <table class="bl-table hm-narrow">
                <tr><td>log<sub>10</sub> P(x) – all paths (Forward)</td><td><strong>${this.l10(f.logp)}</strong></td></tr>
                <tr><td>log<sub>10</sub> P(x, π*) – best path only (Viterbi)</td><td>${this.l10(this.vit.logp)}</td></tr>
                <tr><td>P(π* | x) = P(x, π*) / P(x): probability that the best path is exactly right</td><td><strong>${this.V.fmtP(Math.exp(pBest))}</strong></td></tr>
                <tr><td>log<sub>10</sub> of P(x | this HMM) / P(x | random letters, each 1/${A.length})</td><td><strong>${this.V.f2(lo)}</strong></td></tr>
            </table>
            <p>The last line is a <strong>log-odds score</strong>: positive means that the HMM explains the sequence better than random letters do. Does the structure (the segments) matter, or only the composition? <button data-act="shuffle">Compare with the shuffled sequence</button></p>
            <div id="b-shuffle">${shuffled}</div>
            ${this.V.lesson(`<strong>Why add up paths?</strong> The best path usually carries only a small share of the total probability (here ${this.V.fmtP(Math.exp(pBest))}) – many slightly different paths are almost as good. To decide whether a sequence fits a model, all of them count. Summing log-probabilities needs care: log(p + q) = log p + log(1 + 10<sup>log q − log p</sup>) ("log-sum-exp"). <strong>This is how profile HMMs score sequences</strong>: HMMER reports the Forward score of the sequence against the family model relative to a random model (part 3).`)}`;
    }

    shuffleCompare() {
        const rng = new this.H.Rng((Math.random() * 1e9) | 0);
        const sh = rng.shuffle(this.seq.split('')).join('');
        const A = this.model.alphabet.length;
        const lo = s => (this.H.forward(this.model, s).logp - s.length * Math.log(1 / A)) / Math.LN10;
        const a = lo(this.seq), b = lo(sh);
        const html = `${this.V.seqStrip(sh, null, this.model, { label: 'shuffled' })}
            <p>Log-odds: original <strong>${this.V.f2(a)}</strong>, shuffled <strong>${this.V.f2(b)}</strong>. ${a > b ? 'Shuffling keeps the composition but destroys the segments, and the score drops: the HMM rewards symbols that cluster the way its states predict.' : 'Here the shuffled sequence scores about as well – with this model and sequence the segments are not distinct enough to matter. Try a longer sequence or more different states.'}</p>`;
        this.shuffled = { orig: this.seq, html };
        this.$('b-shuffle').innerHTML = html;
    }

    // ------------------------------------------------------------ step 6
    stepPosterior() {
        const m = this.model, P = this.post;
        const bands = [];
        if (this.truePath) bands.push({ label: 'true', path: this.truePath });
        bands.push({ label: 'Viterbi', path: this.vit.path });
        bands.push({ label: 'posterior', path: P.decoded });
        const unsure = P.post[1].filter(p => p > 0.2 && p < 0.8).length;
        const aV = this.accuracy(this.vit.path), aP = this.accuracy(P.decoded);
        return `<h3>Posterior decoding: how sure are we at each position?</h3>
            <p>Viterbi gives one path but no measure of confidence. Instead we can ask, for every position separately: <em>what is the probability that the state at position i was k, given the whole sequence?</em> It is the share of P(x) that comes from paths passing through state k at position i:</p>
            <p class="hm-formula">P(π<sub>i</sub> = k | x) = f<sub>k</sub>(i) · b<sub>k</sub>(i) / P(x)</p>
            <p>f<sub>k</sub>(i) is the Forward value (all paths from the start up to position i in state k). b<sub>k</sub>(i) comes from the <strong>Backward algorithm</strong>, the mirror image run from the end: the probability of all ways to emit the rest, x<sub>i+1</sub>…x<sub>L</sub>, starting from state k at position i: b<sub>k</sub>(i) = Σ<sub>l</sub> a<sub>kl</sub> e<sub>l</sub>(x<sub>i+1</sub>) b<sub>l</sub>(i+1).</p>
            <div class="hm-plot-wrap">${this.V.posteriorPlot(P.post, 1, m, bands)}</div>
            <table class="bl-table hm-narrow">
                <tr><th></th><th>agreement with the true path</th></tr>
                <tr><td>Viterbi path</td><td>${aV === null ? 'unknown' : (aV * 100).toFixed(0) + ' %'}</td></tr>
                <tr><td>posterior decoding (most probable state at each position)</td><td>${aP === null ? 'unknown' : (aP * 100).toFixed(0) + ' %'}</td></tr>
                <tr><td>positions where neither state reaches 80 %</td><td>${unsure} of ${this.seq.length}</td></tr>
            </table>
            ${this.V.lesson(`<strong>Viterbi or posterior?</strong> Viterbi gives the single most probable <em>path</em>, a consistent story. Posterior decoding picks the most probable <em>state at each position</em> independently: it maximises the expected number of correct positions, but the resulting path can be improbable as a whole. The curve itself is the most useful output – values near 0 or 1 are confident calls, values near 0.5 are guesses. The same idea gives the confidence of every aligned residue pair in part 2 and HMMER's <code>PP</code> line (posterior probability of each aligned residue) in part 3.`)}`;
    }

    // ------------------------------------------------------------ step 7
    stepLearning() {
        return `<h3>Where do the probabilities come from?</h3>
            <p><strong>With labelled data</strong> (sequences with known paths, e.g. experimentally mapped islands) we simply count and divide:</p>
            <p class="hm-formula">a<sub>kl</sub> = A<sub>kl</sub> / Σ<sub>l'</sub> A<sub>kl'</sub> &nbsp;&nbsp;&nbsp; e<sub>k</sub>(b) = E<sub>k</sub>(b) / Σ<sub>b'</sub> E<sub>k</sub>(b')</p>
            <p>where A<sub>kl</sub> counts the k→l transitions and E<sub>k</sub>(b) counts how often state k emitted b. A small <strong>pseudocount</strong> is added to every count so that something never seen does not get probability zero.</p>
            <p><strong>Without the paths</strong> we cannot count – but we can count <em>expected</em> transitions and emissions using the posterior probabilities of step 6 under the current guess of the model, re-estimate, and repeat. This is the <strong>Baum–Welch algorithm</strong> (an EM algorithm). Every round increases P(data | model) until it reaches a (local) maximum.</p>
            <div class="dp-answer-row hm-tight">
                <label for="b-trainN">training sequences:</label>
                <select id="b-trainN">${[1, 3, 10, 30, 100].map(n => `<option ${n === this.trainN ? 'selected' : ''}>${n}</option>`).join('')}</select>
                <span class="dp-hint">× ${Math.max(this.seq.length, 50)} symbols, generated by the current model</span>
                <button class="primary" data-act="train">Generate training data and learn</button>
            </div>
            <div id="b-train"></div>
            ${this.V.lesson(`<strong>What to notice:</strong> with labelled data a handful of sequences gives good estimates, and more data gives better ones. Baum–Welch needs more data, can stop in a local optimum, and does not know which state is which – its "state 1" may be the true "state 2" (label switching). In practice HMMs are trained on labelled or aligned data whenever possible; profile HMMs (part 3) are estimated by counting in a multiple alignment, which plays the role of the known paths.`)}`;
    }

    train() {
        const n = +this.$('b-trainN').value; this.trainN = n;
        const L = Math.max(this.seq.length, 50);
        const rng = new this.H.Rng((Math.random() * 1e9) | 0);
        const data = []; for (let r = 0; r < n; r++) data.push(this.H.sample(this.model, L, rng));
        const counted = this.H.estimate(this.model, data, 1);
        const A = this.model.alphabet.split('');
        // a vague, slightly asymmetric starting guess for Baum–Welch
        const init = this.H.normalizeModel({ alphabet: this.model.alphabet, start: [0.5, 0.5], trans: [[0.8, 0.2], [0.2, 0.8]],
            states: this.model.states.map((st, k) => ({ key: st.key, name: st.name, color: st.color, emit: Object.fromEntries(A.map((a, j) => [a, 1 + 0.15 * (k === 0 ? 1 : -1) * ((j % 2) ? 1 : -1) + 0.1 * rng.next()])) })) });
        const hist = this.H.baumWelch(init, data.map(d => d.seq), 25, 0.1);
        let bw = hist[hist.length - 1].model, swapped = false;
        const dist = (a, b) => A.reduce((s, x) => s + Math.abs(a.emit[x] - b.emit[x]), 0);
        if (dist(bw.states[0], this.model.states[1]) + dist(bw.states[1], this.model.states[0]) < dist(bw.states[0], this.model.states[0]) + dist(bw.states[1], this.model.states[1])) {
            swapped = true;
            bw = { alphabet: bw.alphabet, start: [bw.start[1], bw.start[0]], trans: [[bw.trans[1][1], bw.trans[1][0]], [bw.trans[0][1], bw.trans[0][0]]],
                   states: [Object.assign({}, bw.states[1], { name: this.model.states[0].name, color: this.model.states[0].color }), Object.assign({}, bw.states[0], { name: this.model.states[1].name, color: this.model.states[1].color })] };
        }
        const trueLL = data.reduce((s, d) => s + this.H.forward(this.model, d.seq).logp, 0);
        this.training = { n, L, counted: counted.model, counts: counted.counts, bw, swapped, hist, trueLL };
        this.renderTraining();
    }

    renderTraining() {
        const T = this.training, el = this.$('b-train');
        if (!el || !T) return;
        const m = this.model, A = m.alphabet.split('');
        const rows = [];
        for (let k = 0; k < 2; k++) rows.push([`a: ${this.V.esc(m.states[k].name)} → ${this.V.esc(m.states[k].name)}`, m.trans[k][k], T.counted.trans[k][k], T.bw.trans[k][k], `${T.counts.trans[k][k]} of ${T.counts.trans[k][0] + T.counts.trans[k][1]}`]);
        for (let k = 0; k < 2; k++) for (const a of A) rows.push([`e: ${this.V.esc(m.states[k].name)} emits ${a}`, m.states[k].emit[a], T.counted.states[k].emit[a], T.bw.states[k].emit[a], `${T.counts.emit[k][a]} of ${A.reduce((s, b) => s + T.counts.emit[k][b], 0)}`]);
        const cell = (est, tru) => `<td class="${Math.abs(est - tru) < 0.03 ? 'dp-green' : Math.abs(est - tru) > 0.1 ? 'dp-red' : ''}">${est.toFixed(3)}</td>`;
        el.innerHTML = `<table class="bl-table hm-learn"><tr><th>parameter</th><th>true</th><th>counted (paths known)</th><th>Baum–Welch (paths hidden)</th><th>counts</th></tr>
            ${rows.map(r => `<tr><td>${r[0]}</td><td>${r[1].toFixed(3)}</td>${cell(r[2], r[1])}${cell(r[3], r[1])}<td class="dp-hint">${r[4]}</td></tr>`).join('')}</table>
            <p class="dp-hint">Green: within 0.03 of the truth; red: more than 0.1 off. ${T.n} sequence${T.n > 1 ? 's' : ''} × ${T.L} symbols.${T.swapped ? ' <strong>Baum–Welch came out with the two states swapped</strong> – they have been put back in order here.' : ''}</p>
            <div class="bl-two"><div>${this.V.linePlot(T.hist.map(h => h.loglik / Math.LN10), { xlabel: 'Baum–Welch iteration', ylabel: 'log10 P(data | model)', hline: T.trueLL / Math.LN10, hlineLabel: 'true model' })}</div>
            <div><p class="dp-hint">The likelihood of the training data never decreases from one iteration to the next. If the curve ends above the dashed line of the true model, Baum–Welch has <em>overfitted</em> the particular training sequences – likely with little data.</p></div></div>`;
    }

    // ------------------------------------------------------------ events
    onClick(e) {
        const b = e.target.closest('[data-act]');
        if (b) {
            const act = b.dataset.act;
            if (act === 'animate') this.animate();
            else if (act === 'generate') { this.generate(); }
            else if (act === 'toggle-truth') { this.showTruth = !this.showTruth; this.showStep(2); }
            else if (act === 'path-all') { this.userPath.fill(+b.dataset.k); this.showStep(3); }
            else if (act === 'path-true') { this.userPath = this.truePath.slice(); this.showStep(3); }
            else if (act === 'path-best') { this.userPath = this.vit.path.slice(); this.showStep(3); }
            else if (act === 'reveal') { this.bestRevealed = true; this.showStep(3); }
            else if (act === 'tmode') { const t = this.trellis[b.dataset.kind]; t.mode = b.value; t.k = 0; t.sel = null; this.showStep(this.step); }
            else if (act === 'tstep') { const t = this.trellis[b.dataset.kind]; t.k = Math.min(t.k + +b.dataset.n, this.model.states.length * this.seq.length); this.showStep(this.step); }
            else if (act === 'shuffle') this.shuffleCompare();
            else if (act === 'train') this.train();
            return;
        }
        const td = e.target.closest('td[data-trellis]');
        if (td) {
            const t = this.trellis[td.dataset.trellis];
            if (t.mode === 'full') { t.sel = { k: +td.dataset.k, i: +td.dataset.i }; this.showStep(this.step); }
        }
    }

    onPaintStart(e) {
        const r = e.target.closest('.hm-paint .hm-click');
        if (!r) return;
        e.preventDefault();
        const i = +r.dataset.i;
        this.painting = 1 - this.userPath[i];
        this.userPath[i] = this.painting;
        this.paintRefresh();
    }
    onPaintMove(e) {
        if (this.painting === null || this.painting === undefined) return;
        const r = e.target.closest('.hm-paint .hm-click');
        if (!r) return;
        const i = +r.dataset.i;
        if (this.userPath[i] !== this.painting) { this.userPath[i] = this.painting; this.paintRefresh(); }
    }
    // re-render step 3 but keep painting (the strip is rebuilt, so the drag continues on the new elements)
    paintRefresh() { const keep = this.painting; this.showStep(3); this.painting = keep; }
}
